# Production profile values (fill with real credentials/URLs)
auth:
  token-url: "https://api.example.com/api/data/auth"
  user:
    service-key: "PROD_USER_SERVICE_KEY"
  organization:
    service-key: "PROD_ORG_SERVICE_KEY"
  attend:
    service-key: "PROD_ATTEND_SERVICE_KEY"
  apply:
    service-key: "PROD_APPLY_SERVICE_KEY"
  account:
    service-key: "PROD_ACCOUNT_SERVICE_KEY"

endpoints:
  user:
    list-url: "https://api.example.com/users"
    request-payload: '{"date":"{date}"}'
  organization:
    list-url: "https://api.example.com/organizations"
    request-payload: '{"date":"{date}"}'
  attend:
    by-user-url-template: "https://api.example.com/attend"
    by-user-payload-template: '{"userId": "{userId}", "date":"{date}"}'
  apply:
    by-user-url-template: "https://api.example.com/apply"
    by-user-payload-template: '{"userId": "{userId}", "date":"{date}"}'
  account:
    by-user-url-template: "https://api.example.com/accounts"
    by-user-payload-template: '{"userId": "{userId}", "date":"{date}"}'
