# Development profile values (example placeholders)
auth:
  user:
    service-key: "DEV_USER_SERVICE_KEY"
    token-url: "https://dev-auth.example.com/user/token"
  organization:
    service-key: "DEV_ORG_SERVICE_KEY"
    token-url: "https://dev-auth.example.com/org/token"
  attend:
    service-key: "DEV_ATTEND_SERVICE_KEY"
    token-url: "https://dev-auth.example.com/attend/token"
  apply:
    service-key: "DEV_APPLY_SERVICE_KEY"
    token-url: "https://dev-auth.example.com/apply/token"
  account:
    service-key: "DEV_ACCOUNT_SERVICE_KEY"
    token-url: "https://dev-auth.example.com/account/token"

endpoints:
  user:
    list-url: "https://dev-api.example.com/users"
    request-payload: '{"date":"{request_date}"}'
  organization:
    list-url: "https://dev-api.example.com/organizations"
    request-payload: '{"date":"{request_date}"}'
  attend:
    by-user-url-template: "https://dev-api.example.com/attend"
    by-user-payload-template: '{"userId": "{userId}", "date":"{request_date}"}'
  apply:
    by-user-url-template: "https://dev-api.example.com/apply"
    by-user-payload-template: '{"userId": "{userId}", "date":"{request_date}"}'
  account:
    by-user-url-template: "https://dev-api.example.com/accounts"
    by-user-payload-template: '{"userId": "{userId}", "date":"{request_date}"}'
