# Production profile values (fill with real credentials/URLs)
auth:
  user:
    service-key: "PROD_USER_SERVICE_KEY"
    token-url: "https://auth.example.com/user/token"
  organization:
    service-key: "PROD_ORG_SERVICE_KEY"
    token-url: "https://auth.example.com/org/token"
  attend:
    service-key: "PROD_ATTEND_SERVICE_KEY"
    token-url: "https://auth.example.com/attend/token"
  apply:
    service-key: "PROD_APPLY_SERVICE_KEY"
    token-url: "https://auth.example.com/apply/token"
  account:
    service-key: "PROD_ACCOUNT_SERVICE_KEY"
    token-url: "https://auth.example.com/account/token"

endpoints:
  user:
    list-url: "https://api.example.com/users"
  organization:
    list-url: "https://api.example.com/organizations"
  attend:
    by-user-url-template: "https://api.example.com/attend?userId={userId}"
  apply:
    by-user-url-template: "https://api.example.com/apply?userId={userId}"
  account:
    by-user-url-template: "https://api.example.com/accounts?userId={userId}"

