# Development profile values (example placeholders)
auth:
  token-url: "https://dev-api.example.com/api/data/auth"
  user:
    service-key: "DEV_USER_SERVICE_KEY"
  organization:
    service-key: "DEV_ORG_SERVICE_KEY"
  attend:
    service-key: "DEV_ATTEND_SERVICE_KEY"
  apply:
    service-key: "DEV_APPLY_SERVICE_KEY"
  account:
    service-key: "DEV_ACCOUNT_SERVICE_KEY"

endpoints:
  user:
    url: "https://dev-api.example.com/users"
    request-payload: '{"date":"{date}"}'
  organization:
    url: "https://dev-api.example.com/organizations"
    request-payload: '{"date":"{date}"}'
  attend:
    url: "https://dev-api.example.com/attend"
    request-payload: '{"date":"{date}"}'
  apply:
    url: "https://dev-api.example.com/apply"
    request-payload: '{"date":"{date}"}'
  account:
    url: "https://dev-api.example.com/accounts"
    request-payload: '{"date":"{date}"}'
